name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |

          SHORT_SHA=$(git describe --always --dirty)
          BRANCH_NAME_RAW=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
          BRANCH=$(echo $BRANCH_NAME_RAW | tr -c '[:alnum:]_-' '-')
          
          TAG="${BRANCH}${SHORT_SHA}"
          echo "Building tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.title=OIDC Authorizer
            org.opencontainers.image.description=OIDC JWT token authorizer for AWS API Gateway
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.meta.outputs.tag }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
          build-args: |
            OTEL_SERVICE_NAME=oidc-authorizer
            OTEL_SERVICE_VERSION=${{ steps.meta.outputs.tag }}
